// Upload generated bytes to Cloudflare R2 (S3 API), return a public/signed URL.
import { S3Client, PutObjectCommand } from "@aws-sdk/client-s3";

const s3 = new S3Client({
  region: "auto",
  endpoint: process.env.R2_ENDPOINT!, // https://<acct>.r2.cloudflarestorage.com
  credentials: {
    accessKeyId: process.env.R2_ACCESS_KEY_ID!,
    secretAccessKey: process.env.R2_SECRET_ACCESS_KEY!,
  },
});

const MIME: Record<string, string> = {
  png: "image/png", jpg: "image/jpeg", webp: "image/webp",
  mp4: "video/mp4", webm: "video/webm", gif: "image/gif",
  wav: "audio/wav", mp3: "audio/mpeg", flac: "audio/flac",
};

export async function putObject(key: string, bytes: Buffer, ext: string) {
  await s3.send(new PutObjectCommand({
    Bucket: process.env.R2_BUCKET!,
    Key: key,
    Body: bytes,
    ContentType: MIME[ext] ?? "application/octet-stream",
  }));
  // Requires the bucket bound to a public R2.dev domain or a CDN custom domain.
  return `${process.env.R2_PUBLIC_BASE}/${key}`;
}
